package Controladores;

public enum NTYPE {

    CAM_UPDATE, CAM_INSERT, CAM_DELETE, VUEL_INSERT, VUEL_ERROR1, 
    INF_ADD, INF_S_ARR,INF_C_ARR, INF_S_DEP,INF_C_DEP,INF_REFRESH, INF_DELAY, INF_CRASH,
    ATM_CRASH, ATM_REFRESH, ATM_DAMAGED,
    REFRESH,
    TOR_DELAY, TOR_CRASH

}
