package Datos;

public enum NTYPE {

    CAM_UPDATE, CAM_INSERT, CAM_DELETE, CAM_REFRESH,
    ALRM_CLOSE,
    ATM_CRASH, ATM_REFRESH, ATM_DAMAGED,
    REFRESH,
    TOR_DELAY, TOR_CRASH, INF_REFRESH,

}
