package Utils;

public enum NTYPE {

    CAM_UPDATE, CAM_INSERT, CAM_DELETE, VUEL_INSERT, VUEL_ERROR1, 
    ATM_CRASH, ATM_REFRESH, ATM_DAMAGED,
    REFRESH,
    TOR_DELAY, TOR_CRASH, INF_REFRESH,

}
